# Site settings
title: Choi Minhwa's resume
description: Choi Minhwa's resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Choi Minhwa
user_description: I am interested in AI technology such as machine learning and deep learning, and I am working on several projects related to itğŸ¤–. I use Python as my main language for developmentğŸ‘©ğŸ»â€ğŸ’». Then take your time and have a good time watchingğŸ’œ!
user_title: Data scientist
email: natallia01@naver.com
twitter_username: lorem_ipsum
github_username:  alsghk05
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
